version: "2.1"

networks:
  # docker network create aether_internal
  aether:
    external:
      name: aether_internal

volumes:
  # docker volume create aether_database_data
  database_data:
    external:
      name: aether_database_data

services:

  # ---------------------------------
  # Databases
  # ---------------------------------

  db:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - aether

  minio:
    extends:
      file: ./docker-compose-base.yml
      service: minio-base
    networks:
      - aether

  # ---------------------------------
  # Aether kernel
  # ---------------------------------

  kernel:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      aether:
        aliases:
          - kernel.aether.local
    environment:
      CSRF_COOKIE_DOMAIN: .clinics.eha.ng

  # ---------------------------------
  # Aether UI
  # ---------------------------------

  ui:
    extends:
      file: ./docker-compose-base.yml
      service: ui-base
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      aether:
        aliases:
          - ui.aether.local
    environment:
      CSRF_COOKIE_DOMAIN: .clinics.eha.ng

  # ---------------------------------
  # Aether ODK Module
  # ---------------------------------

  odk:
    extends:
      file: ./docker-compose-base.yml
      service: odk-base
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      aether:
        aliases:
          - odk.aether.local
    environment:
      CSRF_COOKIE_DOMAIN: .clinics.eha.ng

  # ---------------------------------
  # NGINX
  # ---------------------------------

  nginx:
    extends:
      file: ./docker-compose-base.yml
      service: nginx-base
    networks:
      - aether
