# Registration and Generation of Entities
version: "2.1"

networks:
  aether:
    external:
      name: aether_internal

services:

  # ---------------------------------
  # Mock Data Container
  # ---------------------------------
  assets:
    extends:
      file: ./docker-compose-base.yml
      service: assets-base
    networks:
      - aether
