version: "2.1"

networks:
  aether:
    external:
      name: aether_internal

volumes:
  # docker volumes to support Kafka
  kafka-data:
    external:
      name: aether_kafka_data
      
  zk-data:
    external:
      name: aether_zk_data

  zk-txn-logs:
    external:
      name: aether_zk_logs

services:

  # ---------------------------------
  # Kafka & Zookeeper
  # ---------------------------------

  zookeeper:
    extends:
      file: ./docker-compose-base.yml
      service: zookeeper-base
    restart: on-failure
    networks:
      - aether
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-txn-logs:/var/lib/zookeeper/log

  kafka:
    extends:
      file: ./docker-compose-base.yml
      service: kafka-base
    restart: on-failure
    depends_on:
      - zookeeper
    links:
      - zookeeper
    networks:
      - aether
    volumes:
      - kafka-data:/var/lib/kafka/data

  # ---------------------------------
  # Aether Kafka Producer
  # ---------------------------------

  producer:
    extends:
      file: ./docker-compose-base.yml
      service: aether-producer-base
    restart: on-failure
    links:
      - kafka
      - zookeeper
    networks:
      - aether
