version: "2.1"

networks:
  test:
    external:
      name: aether_test

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db-test:
    image: postgres:9.6-alpine
    networks:
      - test

  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel-test:
    extends:
      file: docker-compose-base.yml
      service: kernel-base
    environment:
      TESTING: "true"
      RDS_DB_NAME: aether-kernel-test
      RDS_HOSTNAME: db-test
      AETHER_KERNEL_TOKEN: 0F3560FE5F9D0E9C04833FDA0CEC41DB8B11246A
      WEB_SERVER_PORT: 9001 # Set by uwsgi.ini in volume
    ports:
      - "9001:9001"
    depends_on:
      - db-test
    volumes:
      - ./conf/test/kernel-uwsgi.ini:/code/conf/uwsgi.ini
    networks:
      - test

  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk-test:
    extends:
      file: docker-compose-base.yml
      service: odk-base
    environment:
      TESTING: "true"
      AETHER_KERNEL_URL: http://kernel-test:9001
      RDS_DB_NAME: aether-odk-test
      RDS_HOSTNAME: db-test
      WEB_SERVER_PORT: 9002
      AETHER_ODK_TOKEN: 0F3560FE5F9D0E9C04833FDA0CEC41DB8B11246A
      AETHER_KERNEL_TOKEN: 0F3560FE5F9D0E9C04833FDA0CEC41DB8B11246A
    ports:
      - "9002:9002"
    depends_on:
      - db-test
      - kernel-test
    networks:
      - test

  # ---------------------------------
  # Aether Kafka Containers
  # ---------------------------------



  kafka-test:
    extends:
      file: docker-compose-base.yml
      service: kafka-base
    depends_on:
      - zookeeper-test
    links:
      - zookeeper-test
    ports:
      - "29099:29099"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:32189
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:29099
      ADVERTISED_HOST_NAME: kafka-test
    networks:
      - test

  zookeeper-test:
    extends:
      file: docker-compose-base.yml
      service: zookeeper-base
    environment:
      ZOOKEEPER_CLIENT_PORT: 32189
    networks:
      - test

  # ---------------------------------
  # Aether Kafka Producer
  # ---------------------------------

  producer-test:
    extends:
      file: docker-compose-base.yml
      service: aether-producer-base
    restart: on-failure
    environment:
      PRODUCER_SETTINGS_FILE: /code/producer/test/test.json
    volumes:
      - ./conf/test/producer.json:/code/producer/test/test.json
    links:
      - kafka-test
      - zookeeper-test
    ports:
      - "9005:9005"
    command: start
    networks:
      - test


  # ---------------------------------
  # Gather container
  # ---------------------------------

  # gather-test:
  #   extends:
  #     file: docker-compose-base.yml
  #     service: gather-base
  #   environment:
  #     TESTING: "true"
  #     AETHER_MODULES: "kernel,odk,"
  #     AETHER_KERNEL_URL: http://kernel-test:9001
  #     AETHER_ODK_URL: http://odk-test:9002
  #     RDS_DB_NAME: gather-test
  #     RDS_HOSTNAME: db-test
  #     WEB_SERVER_PORT: 9000
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - db-test
  #     - kernel-test
  #     - odk-test
