version: "2.1"

networks:
  aether:
    external:
      name: aether_internal

volumes:
  # docker volume create gather_database_data
  elastic_data:
    external:
      name: elasticsearch_data

services:

  elasticsearch:
    extends:
      file: docker-compose-base.yml
      service: elasticsearch-base
    networks:
      - aether
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    extends:
      file: docker-compose-base.yml
      service: kibana-base
    depends_on:
      - elasticsearch
    networks:
      - aether

  elasticsearch-consumer:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    environment:
      ELASTICSEARCH_INSTANCE_URLS: "elasticsearch"
      BOOTSTRAP_SERVERS: "kafka:29092"
      CONSUMER_PORT: 9099
      ES_CONSUMER_CONFIG_PATH: "/code/conf/consumer/consumer.json"
      ES_CONSUMER_KAFKA_CONFIG_PATH: "/code/conf/consumer/kafka.json"
    links:
      - elasticsearch
    networks:
      - aether
